services:
  www:
    build:
      dockerfile: ./dockerfile.www
    volumes:
      - "./fastapi_snowflake_challenge:/app/fastapi_snowflake_challenge"
      - "./tests:/app/tests"
      - "./db:/app/db"
      - "./docker/www/prestart.sh:/app/prestart.sh"
    ports:
      - "8888:80"
    environment:
      IS_DEV: true
      RELOAD: true
      SF_USER: "change-me"
      SF_PASSWORD: "change-me"
      SF_ACCOUNT: "sbhwnwx-kc06186"
      SF_DATABASE: "TEST_TASK"
      SF_SCHEMA: "PUBLIC"
